name: Stalebot
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Stale Issues
      uses: actions/stale@v1.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue hasn't had any updates in a while. If this is still a problem, please create a new issue."
        stale-issue-label: "stale"
        days-before-stale: 30
        days-before-close: 7
        exempt-issue-labels: "bug,urgent,feature,pinned,locked"
